export enum SHORTENING_ERROR {
    INVALID_URL = "INVALID_URL"
}

export enum USER_CREATION_ERROR {
    INVALID_DATA = "INVALID_DATA_PROVIDED",
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
    INTERNAL_ERROR = "INTERNAL_ERROR"
}

export enum USER_LISTING_ERROR {
    INTERNAL_ERROR = "INTERNAL_ERROR"
}

export enum USER_LOGIN_ERROR {
    INVALID_DATA_PROVIDED = "INVALID_DATA_PROVIDED"
    ,USER_DOES_NOT_EXIST = "USER_DOES_NOT_EXIST"
    ,NON_ACTIVE_STATUS = "NON_ACTIVE_STATUS"
    ,INCORRECT_PASSWORD = "INCORRECT_PASSWORD"
}

export enum USER_AUTH_ERROR {
    LOGIN_REQUIRED = "LOGIN_REQUIRED",
    INVALID_TOKEN_PROVIDED = "INVALID_TOKEN_PROVIDED",
    ADMIN_PRIVILEDGES_REQUIRED = "ADMIN_PRIVILEDGES_REQUIRED",
    CREATED_ACCOUNT_REQUIRED = "CREATED_ACCOUNT_REQUIRED",
    ACTIVE_STATE_REQUIRED = "ACTIVE_STATE_REQUIRED"
}

export enum REDIRECT_ERROR {
    NOT_FOUND = "URL_NOT_FOUND"
}